In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
import warnings
warnings.filterwarnings("ignore")

In [40]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [41]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [42]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [43]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [44]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [45]:
independent=dataset[['User ID', 'Age', 'EstimatedSalary', 'Gender_Male']]

In [46]:
dependent=dataset[['Purchased']]

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [48]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train, y_train)
y_predict=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_predict)
from sklearn.metrics import classification_report
cl_report=classification_report(y_test, y_predict)
print(cl_report)
print(cm)

              precision    recall  f1-score   support

           0       0.91      0.93      0.92        85
           1       0.87      0.84      0.85        49

    accuracy                           0.90       134
   macro avg       0.89      0.88      0.89       134
weighted avg       0.89      0.90      0.90       134

[[79  6]
 [ 8 41]]


In [49]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()
classifier.fit(X_train, y_train)
y_predict=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_predict)
from sklearn.metrics import classification_report
cl_report=classification_report(y_test, y_predict)
print(cl_report)
print(cm)

              precision    recall  f1-score   support

           0       0.77      0.64      0.70        85
           1       0.52      0.67      0.58        49

    accuracy                           0.65       134
   macro avg       0.64      0.65      0.64       134
weighted avg       0.68      0.65      0.66       134

[[54 31]
 [16 33]]


In [50]:
from sklearn.naive_bayes import BernoulliNB
classifier=BernoulliNB()
classifier.fit(X_train, y_train)
y_predict=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_predict)
from sklearn.metrics import classification_report
cl_report=classification_report(y_test, y_predict)
print(cl_report)
print(cm)

              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134

[[85  0]
 [49  0]]


In [51]:
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier.fit(X_train, y_train)
y_predict = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_predict)
from sklearn.metrics import classification_report
cl_report=classification_report(y_test, y_predict)
print(cl_report)
print(cm)

IndexError: index 15815236 is out of bounds for axis 1 with size 15814817

In [ ]:
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB()
classifier.fit(X_train, y_train)
y_predict = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_predict)
from sklearn.metrics import classification_report
cl_report=classification_report(y_test, y_predict)
print(cl_report)
print(cm)